apiVersion: resource.k8s.io/v1alpha3
kind: ResourceClaimTemplate
metadata:
  namespace: power-dra-driver
  name: nx-gzip
spec:
  spec:
    devices:
      requests:
      - name: nx-gzip
        deviceClassName: nx.device.power.ibm.com