apiVersion: resource.k8s.io/v1alpha3
kind: ResourceSlice
metadata:
  name: nx-gzip-slice-worker-0
  namespace: ex-dra-driver
spec:
  driver: nx.device.power.ibm.com
  nodeName: worker-0
  pool:
    name: worker-0
    generation: 0
    resourceSliceCount: 1
  devices:
  - name: nxgzip0
    basic:
      attributes:
        model:
          string: NX-GZIP-V1
        uuid:
          string: nx-gzip-uuid-001
      capacity:
        memory: "80Gi"
  - name: nxgzip1
    basic:
      attributes:
        model:
          string: NX-GZIP-V2
        uuid:
          string: nx-gzip-uuid-002
      capacity:
        memory: "80Gi"

