apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex-dra-driver-sec
  labels:
    app: ex-dra-driver-sec
spec:
  selector:
    matchLabels:
      app: ex-dra-driver
  template:
    metadata:
      labels:
        app: ex-dra-driver
        template: "1"
    spec:
      resourceClaims:
      - name: nxgzip
        resourceClaimTemplateName: nx-gzip-template-0
      serviceAccount: ex-sa
      serviceAccountName: ex-sa
      containers:
      - name: driver
        image: registry.access.redhat.com/ubi9/ubi:9.6
        imagePullPolicy: IfNotPresent
        command: ["bash", "-c"]
        args: ["export; trap 'exit 0' TERM; sleep 9999 & wait"]
        resources:
          claims:
            - name: nxgzip
          limits:
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        serviceAccount: ex-sa
        serviceAccountName: ex-sa
        securityContext:
          privileged: false
          runAsUser: 1000740022
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
  updateStrategy:
    type: RollingUpdate
