apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: ex-dra-driver

namespace: ex-dra-driver

generatorOptions:
  disableNameSuffixHash: true

resources:
- 01-sa.yaml
- 02-rbac.yaml
- 03-resource-claim-template.yaml
- 04-deployment-first.yaml
- 05-deployment-second.yaml
