apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ex-sa-rbac
  namespace: ex-dra-driver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:restricted
subjects:
- kind: ServiceAccount
  name: ex-sa