---
apiVersion: v1
kind: Pod
metadata:
  namespace: ex-dra-driver
  name: structured-parameters
spec:
  resourceClaims:
  - name: "nxgzip"
    resourceClaimTemplateName: nx-gzip-template
  containers:
  - name: workload
    image: registry.access.redhat.com/ubi9/ubi:9.6
    command: ["/bin/sleep"]
    args:
    - "infinity"
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    resources:
      claims:
      - name: nxgzip
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: false
      runAsUser: 0
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: RuntimeDefault
